{application,elixir_tictactoe,
             [{registered,[]},
              {description,"Core library to build a tictactoe app"},
              {vsn,"0.3.2"},
              {modules,['Elixir.Board','Elixir.Game','Elixir.GameFactory',
                        'Elixir.Player','Elixir.Player.Human',
                        'Elixir.Player.LinearCpu','Elixir.Player.MiniMax',
                        'Elixir.Player.Player.Human',
                        'Elixir.Player.Player.LinearCpu',
                        'Elixir.Player.Player.MiniMax']},
              {applications,[kernel,stdlib,elixir,logger]}]}.